# Generated by Django 4.1.7 on 2023-04-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_order_address_order_phone_alter_order_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
