# Generated by Django 4.1.7 on 2023-04-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_orderdetail_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
