# Generated by Django 4.1.7 on 2023-04-14 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_order_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='ecom.product'),
        ),
    ]
